services:
  app:
    image: oscarfonts/geoserver:2.27.0
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoserver.rule=Host(`geoserver.soldrake.net`)"
      - "traefik.http.routers.geoserver.service=geoserver"
      - "traefik.http.services.geoserver.loadbalancer.server.port=8080"
      - "traefik.http.routers.geoserver.tls=true"
      - "traefik.http.routers.geoserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.geoserver.entryPoints=websecure"
      - "traefik.http.routers.geoserver.middlewares=forwarded-headers"
      - "traefik.http.middlewares.forwarded-headers.headers.customrequestheaders.x-real-ip={{ index .Headers \"X-Forwarded-For\" 0 }}"
      - "traefik.http.middlewares.forwarded-headers.headers.customrequestheaders.x-forwarded-proto={{ index .Headers \"X-Forwarded-Proto\" 0 }}"
    environment:
      GEOSERVER_NODE_OPTS: id:GEOSERVER
      EXTRA_JAVA_OPTS: -Djava.net.preferIPv4Stack=true -DALLOW_ENV_PARAMETRIZATION=true -Xms1G -Xmx5G -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:+UseParallelGC
      PROXY_BASE_URL: https://geoserver.soldrake.net/
      PROXY_BASE_URL_HEADERS: true
      CORS_ALLOWED_ORIGINS: http://localhost:3100/
      SKIP_DEMO_DATA: true
      # POSTGRES_JNDI_ENABLED: true
      # POSTGRES_HOST: xxx.xxx.xxx.xxx
      # POSTGRES_PORT: 5432
      # POSTGRES_DB: database
      # POSTGRES_USERNAME: database_user
      # POSTGRES_PASSWORD: database_pass
      # POSTGRES_JNDI_RESOURCE_NAME: jdbc/db
    volumes:
      - ./additional_libs:/opt/additional_libs:Z
      - data:/opt/geoserver_data:Z
      - mosaicos:/mosaicos
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6148M

  proxy:
    restart: always
    image: traefik
    env_file: .env
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedByDefault=false"

      - "--certificatesresolvers.letsencrypt.acme.email=ivoprovensi1@gmail.com"  # replace with your email
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_acme:/acme
      - traefik_logs:/logs
    ports:
      - "80:80"
      - "443:443"

networks:
  traefik: 

volumes:
  data:
    driver: nfsvol
  mosaicos:
    driver: nfsvol
  traefik_acme:
    driver: nfsvol
  traefik_logs:
    driver: nfsvol
